{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "from bs4 import BeautifulSoup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [],
   "source": [
    "page = requests.get(\"https://fbref.com/en/players/dea698d9/Cristiano-Ronaldo\")\n",
    "soup = BeautifulSoup(page.content,\"html.parser\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "single_year = soup.find_all(id=\"stats\")\n",
    "seasons = [single_year[x].find(class_=\"left\").get_text() for x in range(0,18)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_years = [single_year[x] for x in range(0,18)]\n",
    "find_td = [all_years[x].find_all(\"td\") for x in range(0,18)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 167,
   "metadata": {},
   "outputs": [],
   "source": [
    "age = [find_td[x][0].get_text() for x in range(0,18)]\n",
    "club = [find_td[x][1].get_text() for x in range(0,18)]\n",
    "rank = [find_td[x][4].get_text() for x in range(0,18)]\n",
    "mp = [find_td[x][5].get_text() for x in range(0,18)]\n",
    "f11 = [find_td[x][6].get_text() for x in range(0,18)]\n",
    "mins = [find_td[x][7].get_text() for x in range(0,18)]\n",
    "goals = [find_td[x][8].get_text() for x in range(0,18)]\n",
    "assists = [find_td[x][9].get_text() for x in range(0,18)]\n",
    "pkg = [find_td[x][10].get_text() for x in range(0,18)]\n",
    "pka = [find_td[x][11].get_text() for x in range(0,18)]\n",
    "cy = [find_td[x][12].get_text() for x in range(0,18)]\n",
    "cr = [find_td[x][13].get_text() for x in range(0,18)]\n",
    "gpm = [find_td[x][14].get_text() for x in range(0,18)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 168,
   "metadata": {},
   "outputs": [],
   "source": [
    "ronaldo_stats = pd.DataFrame({\n",
    "    \"Seasons\":seasons,\n",
    "    \"Age\":age,\n",
    "    \"Club\":club,\n",
    "    \"League Rank\":rank,\n",
    "    \"Matches Played\":mp,\n",
    "    \"Matches Started by CR7\":f11,\n",
    "    \"Minutes\":mins,\n",
    "    \"Goals\":goals,\n",
    "    \"Assists\":assists,\n",
    "    \"Penalty Goals\":pkg,\n",
    "    \"Penalties Attempted\":pka,\n",
    "    \"Yellow Cards\":cy,\n",
    "    \"Red Cards\":cr,\n",
    "    \"Goals per 90min\":gpm\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 169,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Seasons</th>\n",
       "      <th>Age</th>\n",
       "      <th>Club</th>\n",
       "      <th>League Rank</th>\n",
       "      <th>Matches Played</th>\n",
       "      <th>Matches Started by CR7</th>\n",
       "      <th>Minutes</th>\n",
       "      <th>Goals</th>\n",
       "      <th>Assists</th>\n",
       "      <th>Penalty Goals</th>\n",
       "      <th>Penalties Attempted</th>\n",
       "      <th>Yellow Cards</th>\n",
       "      <th>Red Cards</th>\n",
       "      <th>Goals per 90min</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2002-2003</td>\n",
       "      <td>17</td>\n",
       "      <td>Sporting CP</td>\n",
       "      <td>3rd</td>\n",
       "      <td>25</td>\n",
       "      <td>11</td>\n",
       "      <td>1,080</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0.25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2003-2004</td>\n",
       "      <td>18</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>3rd</td>\n",
       "      <td>29</td>\n",
       "      <td>15</td>\n",
       "      <td>1,548</td>\n",
       "      <td>4</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2004-2005</td>\n",
       "      <td>19</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>3rd</td>\n",
       "      <td>33</td>\n",
       "      <td>25</td>\n",
       "      <td>2,423</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2005-2006</td>\n",
       "      <td>20</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>2nd</td>\n",
       "      <td>33</td>\n",
       "      <td>24</td>\n",
       "      <td>2,286</td>\n",
       "      <td>9</td>\n",
       "      <td>6</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>8</td>\n",
       "      <td>1</td>\n",
       "      <td>0.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2006-2007</td>\n",
       "      <td>21</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>1st</td>\n",
       "      <td>34</td>\n",
       "      <td>31</td>\n",
       "      <td>2,794</td>\n",
       "      <td>17</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0.55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2007-2008</td>\n",
       "      <td>22</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>1st</td>\n",
       "      <td>34</td>\n",
       "      <td>31</td>\n",
       "      <td>2,747</td>\n",
       "      <td>31</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>1</td>\n",
       "      <td>1.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2008-2009</td>\n",
       "      <td>23</td>\n",
       "      <td>Manchester Utd</td>\n",
       "      <td>1st</td>\n",
       "      <td>33</td>\n",
       "      <td>31</td>\n",
       "      <td>2,743</td>\n",
       "      <td>18</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>0.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2009-2010</td>\n",
       "      <td>24</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>2nd</td>\n",
       "      <td>29</td>\n",
       "      <td>28</td>\n",
       "      <td>2,461</td>\n",
       "      <td>26</td>\n",
       "      <td>7</td>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>2</td>\n",
       "      <td>0.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2010-2011</td>\n",
       "      <td>25</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>2nd</td>\n",
       "      <td>34</td>\n",
       "      <td>32</td>\n",
       "      <td>2,914</td>\n",
       "      <td>40</td>\n",
       "      <td>9</td>\n",
       "      <td>8</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2011-2012</td>\n",
       "      <td>26</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>1st</td>\n",
       "      <td>38</td>\n",
       "      <td>37</td>\n",
       "      <td>3,350</td>\n",
       "      <td>46</td>\n",
       "      <td>12</td>\n",
       "      <td>12</td>\n",
       "      <td>13</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>1.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2012-2013</td>\n",
       "      <td>27</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>2nd</td>\n",
       "      <td>34</td>\n",
       "      <td>30</td>\n",
       "      <td>2,716</td>\n",
       "      <td>34</td>\n",
       "      <td>10</td>\n",
       "      <td>6</td>\n",
       "      <td>7</td>\n",
       "      <td>9</td>\n",
       "      <td>0</td>\n",
       "      <td>1.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2013-2014</td>\n",
       "      <td>28</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>3rd</td>\n",
       "      <td>30</td>\n",
       "      <td>30</td>\n",
       "      <td>2,534</td>\n",
       "      <td>31</td>\n",
       "      <td>9</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>1.10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2014-2015</td>\n",
       "      <td>29</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>2nd</td>\n",
       "      <td>35</td>\n",
       "      <td>35</td>\n",
       "      <td>3,100</td>\n",
       "      <td>48</td>\n",
       "      <td>16</td>\n",
       "      <td>10</td>\n",
       "      <td>12</td>\n",
       "      <td>5</td>\n",
       "      <td>1</td>\n",
       "      <td>1.39</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2015-2016</td>\n",
       "      <td>30</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>2nd</td>\n",
       "      <td>36</td>\n",
       "      <td>36</td>\n",
       "      <td>3,182</td>\n",
       "      <td>35</td>\n",
       "      <td>11</td>\n",
       "      <td>6</td>\n",
       "      <td>9</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2016-2017</td>\n",
       "      <td>31</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>1st</td>\n",
       "      <td>29</td>\n",
       "      <td>29</td>\n",
       "      <td>2,537</td>\n",
       "      <td>25</td>\n",
       "      <td>6</td>\n",
       "      <td>6</td>\n",
       "      <td>7</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>0.89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2017-2018</td>\n",
       "      <td>32</td>\n",
       "      <td>Real Madrid</td>\n",
       "      <td>3rd</td>\n",
       "      <td>27</td>\n",
       "      <td>27</td>\n",
       "      <td>2,288</td>\n",
       "      <td>26</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2018-2019</td>\n",
       "      <td>33</td>\n",
       "      <td>Juventus</td>\n",
       "      <td>1st</td>\n",
       "      <td>31</td>\n",
       "      <td>30</td>\n",
       "      <td>2,688</td>\n",
       "      <td>21</td>\n",
       "      <td>8</td>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0.70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2019-2020</td>\n",
       "      <td>34</td>\n",
       "      <td>Juventus</td>\n",
       "      <td>1st</td>\n",
       "      <td>33</td>\n",
       "      <td>33</td>\n",
       "      <td>2,917</td>\n",
       "      <td>31</td>\n",
       "      <td>5</td>\n",
       "      <td>12</td>\n",
       "      <td>13</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0.96</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      Seasons Age            Club League Rank Matches Played  \\\n",
       "0   2002-2003  17     Sporting CP         3rd             25   \n",
       "1   2003-2004  18  Manchester Utd         3rd             29   \n",
       "2   2004-2005  19  Manchester Utd         3rd             33   \n",
       "3   2005-2006  20  Manchester Utd         2nd             33   \n",
       "4   2006-2007  21  Manchester Utd         1st             34   \n",
       "5   2007-2008  22  Manchester Utd         1st             34   \n",
       "6   2008-2009  23  Manchester Utd         1st             33   \n",
       "7   2009-2010  24     Real Madrid         2nd             29   \n",
       "8   2010-2011  25     Real Madrid         2nd             34   \n",
       "9   2011-2012  26     Real Madrid         1st             38   \n",
       "10  2012-2013  27     Real Madrid         2nd             34   \n",
       "11  2013-2014  28     Real Madrid         3rd             30   \n",
       "12  2014-2015  29     Real Madrid         2nd             35   \n",
       "13  2015-2016  30     Real Madrid         2nd             36   \n",
       "14  2016-2017  31     Real Madrid         1st             29   \n",
       "15  2017-2018  32     Real Madrid         3rd             27   \n",
       "16  2018-2019  33        Juventus         1st             31   \n",
       "17  2019-2020  34        Juventus         1st             33   \n",
       "\n",
       "   Matches Started by CR7 Minutes Goals Assists Penalty Goals  \\\n",
       "0                      11   1,080     3       3             0   \n",
       "1                      15   1,548     4       7             0   \n",
       "2                      25   2,423     5       6             0   \n",
       "3                      24   2,286     9       6             0   \n",
       "4                      31   2,794    17      13             3   \n",
       "5                      31   2,747    31       6             4   \n",
       "6                      31   2,743    18       6             4   \n",
       "7                      28   2,461    26       7             4   \n",
       "8                      32   2,914    40       9             8   \n",
       "9                      37   3,350    46      12            12   \n",
       "10                     30   2,716    34      10             6   \n",
       "11                     30   2,534    31       9             6   \n",
       "12                     35   3,100    48      16            10   \n",
       "13                     36   3,182    35      11             6   \n",
       "14                     29   2,537    25       6             6   \n",
       "15                     27   2,288    26       5             3   \n",
       "16                     30   2,688    21       8             5   \n",
       "17                     33   2,917    31       5            12   \n",
       "\n",
       "   Penalties Attempted Yellow Cards Red Cards Goals per 90min  \n",
       "0                    0            1         0            0.25  \n",
       "1                    0            4         1            0.23  \n",
       "2                    0            4         0            0.19  \n",
       "3                    0            8         1            0.35  \n",
       "4                    4            2         0            0.55  \n",
       "5                    5            5         1            1.02  \n",
       "6                    4            6         1            0.59  \n",
       "7                    5            4         2            0.95  \n",
       "8                    8            2         0            1.24  \n",
       "9                   13            4         0            1.24  \n",
       "10                   7            9         0            1.13  \n",
       "11                   6            4         1            1.10  \n",
       "12                  12            5         1            1.39  \n",
       "13                   9            3         0            0.99  \n",
       "14                   7            4         0            0.89  \n",
       "15                   4            1         0            1.02  \n",
       "16                   6            3         0            0.70  \n",
       "17                  13            3         0            0.96  "
      ]
     },
     "execution_count": 169,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ronaldo_stats"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 170,
   "metadata": {},
   "outputs": [],
   "source": [
    "ronaldo_stats.to_csv(\"Ronaldo_Statistics\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
